version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "MM25Zamanian"
    labels:
      - "dependencies"
    open-pull-requests-limit: 8
