root: true

extends:
  - eslint:recommended
  - google
  - prettier
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:wc/best-practice
  - plugin:lit/all
  - plugin:lit-a11y/recommended

env:
  browser: true
  es2021: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module

plugins:
  - '@typescript-eslint'
  - import
  - wc
  - lit
  - lit-a11y

settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: 'package/*/tsconfig.json'
  wc:
    elementBaseClasses:
      - LitElement
      # TODO: Add other classes

rules:
  wc/guard-super-call: off
  max-len:
    - warn
    - code: 120
  no-eval:
    - error
    - allowIndirect: true
  no-floating-decimal: error
  space-infix-ops: error
  new-cap:
    - error
    - capIsNewExceptionPattern: 'Mixin$'
  '@typescript-eslint/explicit-function-return-type': error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - - parent
          - sibling
          - index
        - type
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  import/no-unresolved: warn
  require-jsdoc: off
  valid-jsdoc: off
